name = "epic-eos-auth-worker" # Choose a name for your worker
main = "src/index.ts"
compatibility_date = "2024-07-25" # Use a recent compatibility date

[vars]
# IMPORTANT: Set EPIC_CLIENT_ID and EPIC_CLIENT_SECRET as secrets using `npx wrangler secret put <KEY>`
# DO NOT commit secrets directly here.
# Example: npx wrangler secret put EPIC_CLIENT_ID
#          npx wrangler secret put EPIC_CLIENT_SECRET

# The URI where Epic Games will redirect the user back AFTER authorization
# This MUST match the redirect URI registered in your Epic Games Application settings
# and the one used in the worker code.
REDIRECT_URI = "https://epic-eos-auth-worker.tpin.workers.dev/callback"

# The URL of your frontend application where the worker will redirect upon successful login
# Use http://localhost:4444 for local development
FRONTEND_URL = "https://epic-auth-login-boilerplate.pages.dev/" 